# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dbplot}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jacob Rothstein"]
  s.date = %q{2010-02-17}
  s.default_executable = %q{dbplot}
  s.description = %q{ruby glue between sql and r (ggplot2)}
  s.email = %q{github@jacobrothstein.com}
  s.executables = ["dbplot"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "bin/dbplot",
     "dbplot.gemspec",
     "lib/dbplot.rb",
     "lib/dbplot/runner.rb",
     "lib/dbplot/template.r.erb",
     "test/dbplot_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/jbr/dbplot}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{dbplot provides a sql-like interface to ggplot2}
  s.test_files = [
    "test/dbplot_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<enumerable-proxy>, [">= 0"])
    else
      s.add_dependency(%q<enumerable-proxy>, [">= 0"])
    end
  else
    s.add_dependency(%q<enumerable-proxy>, [">= 0"])
  end
end

